(in-package #:org.shirakumo.fraf.trial)

#+windows
(define-gamepad acme (3727 18)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad afterglow-ps3-controller (6708 2102)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+windows
(define-gamepad gamestop-gamepad (65535 0)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad generic-directinput-controller (1133 49686)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad horipad-4 (3853 110)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+windows
(define-gamepad logitech-f710-gamepad (1133 49689)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad ps3-controller (34952 776)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :b)
    ( 2 :a)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :left)
    (10 :right)
    (11 :start)
    (12 :home)))

#+windows
(define-gamepad ps3-controller-2 (1356 616)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :select)
    ( 1 :left)
    ( 2 :right)
    ( 3 :start)
    ( 4 :dpad-up)
    ( 5 :dpad-right)
    ( 6 :dpad-down)
    ( 7 :dpad-left)
    ( 8 :l2)
    ( 9 :r2)
    (10 :l1)
    (11 :r1)
    (12 :y)
    (13 :b)
    (14 :a)
    (15 :x)
    (16 :home)))

#+windows
(define-gamepad ps3-dualshock (2341 5)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :b)
    ( 2 :a)
    ( 3 :y)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :start)
    ( 9 :select)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad sony-dualshock-4 (1356 1476)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+windows
(define-gamepad sony-dualshock-4-2 (1356 2508)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+windows
(define-gamepad sony-dualshock-4-wireless-adaptor (1356 2976)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+windows
(define-gamepad logitech-rumblepad-2-usb (1133 49688)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad ouya-controller (10294 1)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :y)
    ( 3 :b)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :dpad-up)
    ( 9 :dpad-down)
    (10 :dpad-left)
    (11 :dpad-right)
    (12 :l2)
    (13 :r2)
    (14 :start)
    (15 :home)))

#+windows
(define-gamepad thrustmaster-firestorm-dual-power (1103 45824)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :home)
    ( 9 :select)
    (10 :start)
    (11 :left)
    (12 :right)))

#+windows
(define-gamepad retrousbcom-retropad (61440 3)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :select)
    ( 3 :start)
    ( 4 :y)
    ( 5 :b)
    ( 6 :l1)
    ( 7 :r1)))

#+windows
(define-gamepad retrousbcom-super-retroport (61440 241)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :select)
    ( 3 :start)
    ( 4 :y)
    ( 5 :b)
    ( 6 :l1)
    ( 7 :r1)))

#+windows
(define-gamepad gamepad-pro-usb (1064 16385)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)))

#+windows
(define-gamepad sven-x-pad (4607 13105)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :y)
    ( 2 :a)
    ( 3 :b)
    ( 4 :select)
    ( 5 :start)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :l2)
    ( 9 :r2)))

#+windows
(define-gamepad piranha-xtreme (3727 3)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad multilaser-js071-usb (3727 12557)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad ps2-usb (2064 3)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 4 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad g-shark-gs-gp702 (121 6)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad nyko-airflo (4683 19713)
  (:axes
    ( 0 :left)
    ( 2 :right)
    ( 3 :l1))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :home)))

#+windows
(define-gamepad powera-pro-ex (8406 51821)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+windows
(define-gamepad saitek-p2500 (1699 65292)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :y)
    ( 2 :a)
    ( 3 :b)
    ( 4 :start)
    ( 5 :select)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :left)
    ( 9 :right)
    (10 :home)))

#+windows
(define-gamepad thrustmaster-dual-analog-32 (1103 45845)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad rock-candy-gamepad-for-ps3 (3695 286)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+windows
(define-gamepad ibuffalo-usb-2-axis-8-button-gamepad (1411 8288)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 2 :y)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)))

#+windows
(define-gamepad ps1-usb (2064 1)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad ipega-pg-9023 (6473 1026)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 3 :x)
    ( 4 :y)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :l2)
    ( 9 :r2)
    (10 :select)
    (11 :start)
    (13 :left)
    (14 :right)))

#+windows
(define-gamepad dual-trigger-3-in-1 (1103 45859)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad hatsune-miku-sho-controller (3853 73)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+windows
(define-gamepad mayflash-gamecube-controller-adapter (121 6211)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-h))
  (:buttons
    ( 0 :right)
    ( 0 :left)
    ( 0 :home)
    ( 0 :select)
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 7 :r1)
    ( 9 :start)))

#+windows
(define-gamepad mayflash-wiiu-pro-game-controller-adapter-dinput (121 6144)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad mayflash-wii-classic-controller (2341 1000)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 2 :y)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-left)
    (13 :dpad-down)
    (14 :dpad-right)))

#+windows
(define-gamepad saitek-p480-rumble-pad (3888 272)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :x)
    ( 1 :y)
    ( 2 :a)
    ( 3 :b)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad 8bitdo-sfc30-gamepad (10256 9)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 3 :y)
    ( 4 :x)
    ( 6 :l1)
    ( 7 :r1)
    (10 :select)
    (11 :start)))

#+windows
(define-gamepad usb-vibration-joystick-bm (9571 1315)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+windows
(define-gamepad 8bitdo-nes30-pro-wireless (14368 9)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 3 :x)
    ( 4 :y)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :l2)
    ( 9 :r2)
    (10 :select)
    (11 :start)
    (13 :left)
    (14 :right)))

#+windows
(define-gamepad 8bitdo-nes30-pro-usb (8194 36864)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 3 :x)
    ( 4 :y)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :l2)
    ( 9 :r2)
    (10 :select)
    (11 :start)
    (13 :left)
    (14 :right)))

#+windows
(define-gamepad exeq-rf-usb-gamepad-8206 (6708 2049)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 7 :right)
    ( 8 :select)
    ( 8 :left)
    ( 9 :start)))

#+windows
(define-gamepad battalife-joystick (4544 21011)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :l1)
    ( 1 :r1)
    ( 2 :select)
    ( 3 :start)
    ( 4 :x)
    ( 5 :y)
    ( 6 :a)
    ( 7 :b)))

#+windows
(define-gamepad next-classic-usb-game-controller (2064 58625)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 8 :select)
    ( 9 :start)))

#+darwin
(define-gamepad gamestop-gamepad (21319 28001)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+darwin
(define-gamepad logitech-f310-gamepad-dinput (0 49686)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+darwin
(define-gamepad logitech-f510-gamepad-dinput (0 49688)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+darwin
(define-gamepad logitech-f710-gamepad-xinput (0 49695)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :start)
    ( 9 :select)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-down)
    (13 :dpad-left)
    (14 :dpad-right)))

#+darwin
(define-gamepad logitech-wireless-gamepad-dinput (0 49689)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+darwin
(define-gamepad ps3-controller (0 616)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :select)
    ( 1 :left)
    ( 2 :right)
    ( 3 :start)
    ( 4 :dpad-up)
    ( 5 :dpad-right)
    ( 6 :dpad-down)
    ( 7 :dpad-left)
    ( 8 :l2)
    ( 9 :r2)
    (10 :l1)
    (11 :r1)
    (12 :y)
    (13 :b)
    (14 :a)
    (15 :x)
    (16 :home)))

#+darwin
(define-gamepad sony-dualshock-4 (0 1476)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+darwin
(define-gamepad sony-dualshock-4-v2 (0 2508)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+darwin
(define-gamepad x360-controller (0 654)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :start)
    ( 9 :select)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-down)
    (13 :dpad-left)
    (14 :dpad-right)))

#+darwin
(define-gamepad razer-onza-tournament (0 64768)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :start)
    ( 9 :select)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-down)
    (13 :dpad-left)
    (14 :dpad-right)))

#+darwin
(define-gamepad thrustmaster-firestorm-dual-power (0 45824)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :home)
    ( 9 :select)
    (10 :start)
    (11 :left)))

#+darwin
(define-gamepad piranha-xtreme (0 3)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+darwin
(define-gamepad hori-gem-pad-3 (0 77)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+darwin
(define-gamepad g-shark-gp-702 (0 6)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+darwin
(define-gamepad thrustmaster-dual-analog-32 (0 45845)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+darwin
(define-gamepad gamestop-bb-070-x360-controller (0 63745)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :start)
    ( 9 :select)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-down)
    (13 :dpad-left)
    (14 :dpad-right)))

#+darwin
(define-gamepad wii-remote (26967 29807)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :dpad-left)
    ( 1 :dpad-right)
    ( 2 :dpad-up)
    ( 3 :dpad-down)
    ( 4 :a)
    ( 5 :b)
    ( 6 :start)
    ( 7 :select)
    ( 8 :home)
    ( 9 :y)
    (10 :x)
    (11 :l1)
    (12 :l2)))

#+darwin
(define-gamepad ibuffalo-usb-2-axis-8-button-gamepad (0 8288)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 2 :y)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)))

#+darwin
(define-gamepad tomee-snes-usb-controller (0 53269)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 8 :select)
    ( 9 :start)))

#+darwin
(define-gamepad retrolink-classic-controller (0 17)
  (:axes
    ( 3 :left-h)
    ( 4 :left-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 8 :select)
    ( 9 :start)))

#+darwin
(define-gamepad xbox-one-wired-controller (0 733)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :start)
    ( 9 :select)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-down)
    (13 :dpad-left)
    (14 :dpad-right)))

#+darwin
(define-gamepad xbox-wireless-controller (0 746)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :start)
    ( 9 :select)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-down)
    (13 :dpad-left)
    (14 :dpad-right)))

#+darwin
(define-gamepad xbox-wireless-controller-2 (0 736)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :left)
    ( 9 :right)
    (10 :home)))

#+darwin
(define-gamepad mayflash-wiiu-pro-game-controller-adapter-dinput (0 6144)
  (:axes
    ( 0 :left-h)
    ( 4 :left-v)
    ( 8 :right-h)
    (12 :right-v))
  (:buttons
    ( 0 :x)
    ( 4 :a)
    ( 8 :b)
    (12 :y)
    (16 :l1)
    (20 :r1)
    (24 :l2)
    (28 :r2)
    (32 :select)
    (36 :start)
    (40 :left)
    (44 :right)))

#+darwin
(define-gamepad mayflash-wii-classic-controller (0 1000)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 2 :y)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :home)
    (11 :dpad-up)
    (12 :dpad-left)
    (13 :dpad-down)
    (14 :dpad-right)))

#+darwin
(define-gamepad sfc30-joystick (0 43809)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 3 :y)
    ( 4 :x)
    ( 6 :l1)
    ( 7 :r1)
    (10 :select)
    (11 :start)))

#+darwin
(define-gamepad sega-saturn-usb-gamepad (0 266)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :home)
    ( 3 :x)
    ( 4 :y)
    ( 5 :select)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :start)))

#+darwin
(define-gamepad sega-saturn (0 1406)
  (:axes
    ( 0 :left-h)
    ( 2 :left-v)
    ( 4 :r2)
    ( 5 :l2))
  (:buttons
    ( 0 :x)
    ( 2 :a)
    ( 4 :b)
    ( 6 :y)
    ( 8 :l1)
    ( 9 :r1)
    (10 :l2)
    (11 :r2)
    (13 :start)
    (14 :dpad-right)
    (15 :dpad-left)
    (16 :dpad-down)
    (17 :dpad-up)))

#+darwin
(define-gamepad 8bitdo-sfc30-gamepad (0 9)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 3 :y)
    ( 4 :x)
    ( 6 :l1)
    ( 7 :r1)
    (10 :select)
    (11 :start)))

#+darwin
(define-gamepad mc-cthulhu (0 53198)
  (:axes)
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)))

#+darwin
(define-gamepad horipad-fps-plus-4 (0 102)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+linux
(define-gamepad gamestop-gamepad (21319 28001)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad jess-technology-usb-game-controller (8890 4128)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)))

#+linux
(define-gamepad logitech-cordless-rumblepad-2 (1133 49689)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad logitech-f310-gamepad-xinput (1133 49693)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad logitech-f310-gamepad-dinput (1133 49686)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad logitech-f510-gamepad-xinput (1133 49694)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad logitech-f710-gamepad-xinput (1133 49695)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad ps3-controller (1356 616)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :select)
    ( 1 :left)
    ( 2 :right)
    ( 3 :start)
    ( 4 :dpad-up)
    ( 5 :dpad-right)
    ( 6 :dpad-down)
    ( 7 :dpad-left)
    ( 8 :l2)
    ( 9 :r2)
    (10 :l1)
    (11 :r1)
    (12 :y)
    (13 :b)
    (14 :a)
    (15 :x)
    (16 :home)))

#+linux
(define-gamepad sony-dualshock-4 (1356 1476)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+linux
(define-gamepad sony-dualshock-4-v2 (1356 2508)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+linux
(define-gamepad sony-dualshock-4-wireless-adaptor (1356 2976)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)
    (13 :select)))

#+linux
(define-gamepad ea-sports-ps3-controller (3695 304)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+linux
(define-gamepad valve-streaming-gamepad (10462 4607)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad x360-controller (1118 654)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad x360-wireless-controller (1118 1817)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)
    (11 :dpad-left)
    (12 :dpad-right)
    (13 :dpad-up)
    (14 :dpad-down)))

#+linux
(define-gamepad twin-usb-ps2-adapter (2064 1)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad saitek-cyborg-v1-game-pad (1699 63011)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+linux
(define-gamepad thrustmaster-2-in-1-dt (1103 45856)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad thrustmaster-dual-trigger-3-in-1 (1103 45859)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad greenasia-inc-usb-joystick- (3727 3)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad greenasia-inc-usb-joystick--2 (3727 18)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad x360-wireless-controller-2 (1118 657)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)
    (11 :dpad-left)
    (12 :dpad-right)
    (13 :dpad-up)
    (14 :dpad-down)))

#+linux
(define-gamepad gamecube-{wisegroup-usb-box} (2342 34952)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v)
    ( 4 :l2)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 6 :r1)
    ( 7 :start)))

#+linux
(define-gamepad logitech-wingman-cordless-rumblepad (1133 49681)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :select)
    ( 3 :x)
    ( 4 :y)
    ( 5 :home)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :start)
    ( 9 :l2)
    (10 :r2)))

#+linux
(define-gamepad logitech-logitech-rumblepad-2-usb (1133 49688)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad moga-pro (8406 3501)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v)
    ( 4 :r2)
    ( 5 :l2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :start)
    ( 7 :left)
    ( 8 :right)))

#+linux
(define-gamepad thrustmaster-run-n-drive-wireless-ps3 (1103 53257)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+linux
(define-gamepad thrustmaster-run-n-drive-wireless (1103 53256)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 5 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad retrousbcom-retropad (61440 3)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :select)
    ( 3 :start)
    ( 4 :y)
    ( 5 :b)
    ( 6 :l1)
    ( 7 :r1)))

#+linux
(define-gamepad retrousbcom-super-retroport (61440 241)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :select)
    ( 3 :start)
    ( 4 :y)
    ( 5 :b)
    ( 6 :l1)
    ( 7 :r1)))

#+linux
(define-gamepad generic-x-box-pad (3695 287)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad gravis-gamepad-pro-usb- (1064 16385)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)))

#+linux
(define-gamepad microsoft-x-box-pad-v2-us (1118 649)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :r1)
    ( 3 :x)
    ( 4 :y)
    ( 5 :l1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :left)
    ( 9 :right)))

#+linux
(define-gamepad microsoft-x-box-pad-japan (1118 645)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :r1)
    ( 3 :x)
    ( 4 :y)
    ( 5 :l1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :left)
    ( 9 :right)))

#+linux
(define-gamepad rock-candy-gamepad-for-ps3 (3695 286)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+linux
(define-gamepad sony-ps2-pad-with-smartjoy-adapter (2341 5)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :start)
    ( 9 :select)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad razer-onza-tournament (5769 64768)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)
    (11 :dpad-left)
    (12 :dpad-right)
    (13 :dpad-up)
    (14 :dpad-down)))

#+linux
(define-gamepad thrustmaster-firestorm-dual-power (1103 45824)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :home)
    ( 9 :select)
    (10 :start)
    (11 :left)
    (12 :right)))

#+linux
(define-gamepad hori-pad-ex-turbo-2 (7085 62721)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+nil
(define-gamepad dragonrise-inc-generic-usb-joystick- 03000000790000000600000010010000
  (:axes
    ( 0 :left-h)
    ( 1 :right-h)
    ( 3 :left-v)
    ( 4 :right-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad super-joy-box-5-pro (26214 34820)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :start)
    ( 9 :select)
    (10 :left)
    (11 :right)
    (12 :dpad-up)
    (13 :dpad-right)
    (14 :dpad-down)
    (15 :dpad-left)))

#+linux
(define-gamepad ouya-game-controller (10294 1)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :y)
    ( 3 :b)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :left)
    ( 7 :right)
    ( 8 :dpad-up)
    ( 9 :dpad-down)
    (10 :dpad-left)
    (11 :dpad-right)
    (14 :home)))

#+linux
(define-gamepad razer-onza-classic-edition (5769 64769)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)
    (11 :dpad-left)
    (12 :dpad-right)
    (13 :dpad-up)
    (14 :dpad-down)))

#+linux
(define-gamepad microsoft-x-box-one-pad (1118 721)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad microsoft-x-box-one-pad-v2 (1118 733)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad retrolink-saturn-classic-controller (121 17)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :home)
    ( 3 :x)
    ( 4 :y)
    ( 5 :select)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :start)))

#+linux
(define-gamepad nintendo-wii-u-pro-controller (1406 816)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :y)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :home)
    (11 :left)
    (12 :right)
    (13 :dpad-up)
    (14 :dpad-down)
    (15 :dpad-left)
    (16 :dpad-right)))

#+linux
(define-gamepad hori-co-ltd-real-arcade-prov3 (3853 34)
  (:axes)
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (12 :home)))

#+linux
(define-gamepad hori-co-ltd-fighting-stick-3 (3853 16)
  (:axes)
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (12 :home)))

#+linux
(define-gamepad goodbetterbest-ltd-usb-controller (9712 33729)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+linux
(define-gamepad xbox-gamepad-userspace-driver (25176 18208)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v)
    ( 4 :r2)
    ( 5 :l2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad pc-game-controller (4607 13105)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad generic-x-box-pad-2 (3695 1043)
  (:axes
    ( 0 :left-h)
    ( 0 :left)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 3 :right)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad saitek-plc-saitek-p3200-rumble-pad (1699 62744)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad ibuffalo-usb-2-axis-8-button-gamepad (1411 8288)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 2 :y)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)))

#+linux
(define-gamepad tomee-snes-usb-controller (4797 53269)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 8 :select)
    ( 9 :start)))

#+linux
(define-gamepad hjc-game-gamepad (4553 22000)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad saitek-p2900-wireless-pad (1699 1036)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :home)
    (10 :left)
    (11 :right)
    (12 :start)))

#+linux
(define-gamepad gamecube-{huijia-usb-box} (6708 63237)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :l2)
    ( 4 :r2)
    ( 5 :right-h))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 7 :r1)
    ( 9 :start)
    (12 :dpad-up)
    (13 :dpad-right)
    (14 :dpad-down)
    (15 :dpad-left)))

#+linux
(define-gamepad jc-u3613m---directinput-mode (1390 8195)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :y)
    ( 2 :a)
    ( 3 :b)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :left)
    ( 9 :right)
    (10 :select)
    (11 :start)
    (12 :home)))

#+linux
(define-gamepad rock-candy-wired-controller-for-xbox-one (3695 326)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad mad-catz-wired-xbox-360-controller (1848 18198)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad afterglow-wired-controller-for-xbox-one (3695 313)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad thrustmaster-dual-analog-4 (1103 45845)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :l2)
    ( 6 :r1)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad 8bitdo-sfc30-gamepad (10256 9)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :b)
    ( 1 :a)
    ( 3 :y)
    ( 4 :x)
    ( 6 :l1)
    ( 7 :r1)
    (10 :select)
    (11 :start)))

#+linux
(define-gamepad hitbox-ps3/pc-analog-mode (5336 25096)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :home)
    (12 :start)))

#+linux
(define-gamepad hori (3853 13)
  (:axes)
  (:buttons
    ( 0 :a)
    ( 1 :x)
    ( 2 :y)
    ( 3 :l1)
    ( 4 :left-h)
    ( 5 :left-v)
    ( 6 :b)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :home)))

#+linux
(define-gamepad mad-catz-xbox-360-controller (7085 61462)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad toodles-2008-chimp-pc/ps3 (5336 52487)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :y)
    ( 3 :x)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)))

#+linux
(define-gamepad interact-gopad-i-73000-fighting-game-layout (1533 12288)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :x)
    ( 1 :y)
    ( 2 :r1)
    ( 3 :a)
    ( 4 :b)
    ( 5 :r2)
    ( 6 :select)
    ( 7 :start)))

#+linux
(define-gamepad nintendo-wiimote (1 1)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :home)
    (11 :left)
    (12 :right)))

#+linux
(define-gamepad saitek-p880 (1699 265)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :x)
    ( 1 :y)
    ( 2 :a)
    ( 3 :b)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :left)
    ( 9 :right)))

#+linux
(define-gamepad logic3-controller (3695 769)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :l2)
    ( 3 :right-h)
    ( 4 :right-v)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)
    ( 9 :left)
    (10 :right)))

#+linux
(define-gamepad mad-catz-ctrlr- (1848 21094)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :x)
    ( 1 :a)
    ( 2 :b)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :l2)
    ( 7 :r2)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)
    (12 :home)))

#+linux
(define-gamepad mad-catz-fightpad-sfxt (7085 61486)
  (:axes
    ( 2 :l2)
    ( 5 :r2))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l1)
    ( 5 :r1)
    ( 6 :select)
    ( 7 :start)
    ( 8 :home)))

#+linux
(define-gamepad 8bitdo-zero-gamepad (1440 12850)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 3 :x)
    ( 4 :y)
    ( 6 :l1)
    ( 7 :r1)
    (10 :select)
    (11 :start)))

#+linux
(define-gamepad next-classic-usb-game-controller (2064 58625)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-h)
    ( 3 :right-v))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 8 :select)
    ( 9 :start)))

#+linux
(define-gamepad usb-gamepad (2064 3)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad vr-box (1452 12850)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v)
    ( 2 :right-v)
    ( 3 :right-h))
  (:buttons
    ( 0 :a)
    ( 1 :b)
    ( 2 :x)
    ( 3 :y)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)
    (10 :left)
    (11 :right)))

#+linux
(define-gamepad microntek-usb-joystick (120 6)
  (:axes
    ( 0 :left-h)
    ( 1 :left-v))
  (:buttons
    ( 0 :y)
    ( 1 :b)
    ( 2 :a)
    ( 3 :x)
    ( 4 :l2)
    ( 5 :r2)
    ( 6 :l1)
    ( 7 :r1)
    ( 8 :select)
    ( 9 :start)))

