(in-package #:org.shirakumo.fraf.trial)

(defvar *static-frictions* (make-hash-table :test 'equal))
(defvar *dynamic-frictions* (make-hash-table :test 'equal))

(defun static-friction (a b)
  (let* ((cons (cons a b))
         (a (gethash cons *static-frictions*)))
    (declare (dynamic-extent cons))
    (cond (a a)
          (T (rotatef (car cons) (cdr cons))
             (or (gethash cons *static-frictions*)
                 (error "Static friction between ~a and ~a is not known." a b))))))

(defun (setf static-friction) (friction a b)
  (setf (gethash (cons a b) *static-frictions*) (float friction 0f0)))

(defun dynamic-friction (a b)
  (let* ((cons (cons a b))
         (found (gethash cons *dynamic-frictions*)))
    (declare (dynamic-extent cons))
    (cond (found found)
          (T (rotatef (car cons) (cdr cons))
             (or (gethash cons *dynamic-frictions*)
                 (error "Dynamic friction between ~a and ~a is not known." a b))))))

(defun (setf dynamic-friction) (friction a b)
  (setf (gethash (cons a b) *dynamic-frictions*) (float friction 0f0)))

(setf (static-friction :wood :wood) 0.5)
(setf (dynamic-friction :wood :wood) 0.5)
(setf (static-friction :wood :concrete) 0.5)
(setf (dynamic-friction :wood :concrete) 0.4)
(setf (static-friction :wood :ice) 0.2)
(setf (dynamic-friction :wood :ice) 0.1)
(setf (static-friction :glass :ice) 0.1)
(setf (dynamic-friction :glass :ice) 0.03)
(setf (static-friction :glass :glass) 0.95)
(setf (dynamic-friction :glass :glass) 0.4)
(setf (static-friction :metal :metal) 0.6)
(setf (dynamic-friction :metal :metal) 0.4)
(setf (static-friction :lubricated-metal :metal) 0.1)
(setf (dynamic-friction :lubricated-metal :metal) 0.05)
(setf (static-friction :rubber :concrete) 1.0)
(setf (dynamic-friction :rubber :concrete) 0.8)
(setf (static-friction :wet-rubber :concrete) 0.7)
(setf (dynamic-friction :wet-rubber :concrete) 0.5)
(setf (static-friction :tire :concrete) 1.5)
(setf (dynamic-friction :tire :concrete) 1.0)
(setf (static-friction :velcro :velcro) 6.0)
(setf (dynamic-friction :velcro :velcro) 4.0)
