(in-package #:org.shirakumo.fraf.trial)

(defun mcol3 (mat n)
  (with-fast-matref (e mat 4)
    (vec3 (e 0 n) (e 1 n) (e 2 n))))

(defun ntransform-inverse (vec3 mat)
  (with-fast-matcase (m mat)
    (mat4
     (let ((x (- (vx3 vec3) (m 3)))
           (y (- (vy3 vec3) (m 7)))
           (z (- (vz3 vec3) (m 11))))
       (setf (vx3 vec3) (+ (* x (m 0)) (* y (m 4)) (* z (m 8))))
       (setf (vy3 vec3) (+ (* x (m 1)) (* y (m 5)) (* z (m 9))))
       (setf (vz3 vec3) (+ (* x (m 2)) (* y (m 6)) (* z (m 10))))))
    (mat3
     (let ((x (vx3 vec3))
           (y (vy3 vec3))
           (z (vz3 vec3)))
       (setf (vx3 vec3) (+ (* x (m 0)) (* y (m 3)) (* z (m 6))))
       (setf (vy3 vec3) (+ (* x (m 1)) (* y (m 4)) (* z (m 7))))
       (setf (vz3 vec3) (+ (* x (m 2)) (* y (m 5)) (* z (m 8)))))))
  vec3)

(defun compute-world-inertia-tensor (iitworld iitbody rotmat)
  (let ((iitworld (marr3 iitworld))
        (iitbody (marr3 iitbody))
        (rotmat (marr4 rotmat)))
    (declare (optimize speed (safety 0)))
    (let ((t4  (+ (* (aref rotmat 0) (aref iitbody 0))
                  (* (aref rotmat 1) (aref iitbody 3))
                  (* (aref rotmat 2) (aref iitbody 6))))
          (t9  (+ (* (aref rotmat 0) (aref iitbody 1))
                  (* (aref rotmat 1) (aref iitbody 4))
                  (* (aref rotmat 2) (aref iitbody 7))))
          (t14 (+ (* (aref rotmat 0) (aref iitbody 2))
                  (* (aref rotmat 1) (aref iitbody 5))
                  (* (aref rotmat 2) (aref iitbody 8))))
          (t28 (+ (* (aref rotmat 4) (aref iitbody 0))
                  (* (aref rotmat 5) (aref iitbody 3))
                  (* (aref rotmat 6) (aref iitbody 6))))
          (t33 (+ (* (aref rotmat 4) (aref iitbody 1))
                  (* (aref rotmat 5) (aref iitbody 4))
                  (* (aref rotmat 6) (aref iitbody 7))))
          (t38 (+ (* (aref rotmat 4) (aref iitbody 2))
                  (* (aref rotmat 5) (aref iitbody 5))
                  (* (aref rotmat 6) (aref iitbody 8))))
          (t52 (+ (* (aref rotmat 8) (aref iitbody 0))
                  (* (aref rotmat 9) (aref iitbody 3))
                  (* (aref rotmat 10) (aref iitbody 6))))
          (t57 (+ (* (aref rotmat 8) (aref iitbody 1))
                  (* (aref rotmat 9) (aref iitbody 4))
                  (* (aref rotmat 10) (aref iitbody 7))))
          (t62 (+ (* (aref rotmat 8) (aref iitbody 2))
                  (* (aref rotmat 9) (aref iitbody 5))
                  (* (aref rotmat 10) (aref iitbody 8)))))
      (setf (aref iitworld 0) (+ (* t4  (aref rotmat 0))
                                 (* t9  (aref rotmat 1))
                                 (* t14 (aref rotmat 2)))
            (aref iitworld 1) (+ (* t4  (aref rotmat 4))
                                 (* t9  (aref rotmat 5))
                                 (* t14 (aref rotmat 6)))
            (aref iitworld 2) (+ (* t4  (aref rotmat 8))
                                 (* t9  (aref rotmat 9))
                                 (* t14 (aref rotmat 10)))
            (aref iitworld 3) (+ (* t28 (aref rotmat 0))
                                 (* t33 (aref rotmat 1))
                                 (* t38 (aref rotmat 2)))
            (aref iitworld 4) (+ (* t28 (aref rotmat 4))
                                 (* t33 (aref rotmat 5))
                                 (* t38 (aref rotmat 6)))
            (aref iitworld 5) (+ (* t28 (aref rotmat 8))
                                 (* t33 (aref rotmat 9))
                                 (* t38 (aref rotmat 10)))
            (aref iitworld 6) (+ (* t52 (aref rotmat 0))
                                 (* t57 (aref rotmat 1))
                                 (* t62 (aref rotmat 2)))
            (aref iitworld 7) (+ (* t52 (aref rotmat 4))
                                 (* t57 (aref rotmat 5))
                                 (* t62 (aref rotmat 6)))
            (aref iitworld 8) (+ (* t52 (aref rotmat 8))
                                 (* t57 (aref rotmat 9))
                                 (* t62 (aref rotmat 10))))))
  iitworld)
