(in-package #:org.shirakumo.fraf.trial)

(defun nq+* (target vector scalar)
  (let ((tmp (quat (* (vx vector) scalar)
                   (* (vy vector) scalar)
                   (* (vz vector) scalar)
                   0.0)))
    (declare (dynamic-extent tmp))
    (nq* tmp target)
    (nq* tmp 0.5)
    (nq+ target tmp)))

(defun nv+* (target vector scalar)
  (setf (vx target) (* (vx vector) scalar))
  (setf (vy target) (* (vy vector) scalar))
  (setf (vz target) (* (vz vector) scalar)))

(defun compute-world-inertia-tensor (iitworld iitbody rotmat)
  (let ((iitworld (marr3 iitworld))
        (iitbody (marr3 iitbody))
        (rotmat (marr4 rotmat)))
    (let ((t4 (+ (* (aref rotmat 0) (aref iitbody 0))
                 (* (aref rotmat 1) (aref iitbody 3))
                 (* (aref rotmat 2) (aref iitbody 6))))
          (t9 (+ (* (aref rotmat 0) (aref iitbody 1))
                 (* (aref rotmat 1) (aref iitbody 4))
                 (* (aref rotmat 2) (aref iitbody 7))))
          (t14 (+ (* (aref rotmat 0) (aref iitbody 2))
                  (* (aref rotmat 1) (aref iitbody 5))
                  (* (aref rotmat 0) (aref iitbody 8))))
          (t28 (+ (* (aref rotmat 4) (aref iitbody 0))
                  (* (aref rotmat 5) (aref iitbody 3))
                  (* (aref rotmat 6) (aref iitbody 6))))
          (t33 (+ (* (aref rotmat 4) (aref iitbody 1))
                  (* (aref rotmat 5) (aref iitbody 4))
                  (* (aref rotmat 6) (aref iitbody 7))))
          (t38 (+ (* (aref rotmat 4) (aref iitbody 2))
                  (* (aref rotmat 5) (aref iitbody 5))
                  (* (aref rotmat 6) (aref iitbody 8))))
          (t52 (+ (* (aref rotmat 8) (aref iitbody 0))
                  (* (aref rotmat 9) (aref iitbody 3))
                  (* (aref rotmat 10) (aref iitbody 6))))
          (t57 (+ (* (aref rotmat 8) (aref iitbody 1))
                  (* (aref rotmat 9) (aref iitbody 4))
                  (* (aref rotmat 10) (aref iitbody 7))))
          (t62 (+ (* (aref rotmat 8) (aref iitbody 2))
                  (* (aref rotmat 9) (aref iitbody 5))
                  (* (aref rotmat 10) (aref iitbody 8)))))
      (setf (aref iitworld 0) (+ (* t4  (aref rotmat 0))
                                 (* t9  (aref rotmat 1))
                                 (* t14 (aref rotmat 2))))
      (setf (aref iitworld 1) (+ (* t4  (aref rotmat 4))
                                 (* t9  (aref rotmat 5))
                                 (* t14 (aref rotmat 6))))
      (setf (aref iitworld 2) (+ (* t4  (aref rotmat 8))
                                 (* t9  (aref rotmat 9))
                                 (* t14 (aref rotmat 10))))
      (setf (aref iitworld 3) (+ (* t28 (aref rotmat 0))
                                 (* t33 (aref rotmat 1))
                                 (* t38 (aref rotmat 2))))
      (setf (aref iitworld 4) (+ (* t28 (aref rotmat 4))
                                 (* t33 (aref rotmat 5))
                                 (* t38 (aref rotmat 6))))
      (setf (aref iitworld 5) (+ (* t28 (aref rotmat 8))
                                 (* t33 (aref rotmat 9))
                                 (* t38 (aref rotmat 10))))
      (setf (aref iitworld 6) (+ (* t52 (aref rotmat 0))
                                 (* t57 (aref rotmat 1))
                                 (* t62 (aref rotmat 2))))
      (setf (aref iitworld 7) (+ (* t52 (aref rotmat 4))
                                 (* t57 (aref rotmat 5))
                                 (* t62 (aref rotmat 6))))
      (setf (aref iitworld 8) (+ (* t52 (aref rotmat 8))
                                 (* t57 (aref rotmat 9))
                                 (* t62 (aref rotmat 10))))
      iitworld)))
