(in-package #:org.shirakumo.fraf.trial)

(defmethod load-image ((path pathname) (type (eql :tga)) &key)
  ;; This library blows and requires a file interface for no good reason.
  (let ((tga (tga:read-tga path)))
    (make-image-source (tga:image-data tga)
                       (tga:image-width tga)
                       (tga:image-height tga)
                       (infer-pixel-type (/ (tga:image-bpp tga)
                                            (tga:image-channels tga))
                                         :unsigned)
                       (ecase (tga:image-channels tga)
                         (1 :red)
                         (2 :gr)
                         (3 :bgr)
                         (4 :bgra)))))
